# Generated by Django 4.2.28 on 2026-02-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="middle_name",
            field=models.CharField(
                blank=True, help_text="Employee's middle name", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, help_text="Employee's phone number", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_completed",
            field=models.BooleanField(
                default=False,
                help_text="Whether the employee has completed their SIRW profile",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_consent_given",
            field=models.BooleanField(
                default=False,
                help_text="Whether the employee has consented to profile data storage",
            ),
        ),
    ]
