# Generated by Django 4.2.28 on 2026-02-06 21:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("model", "Model")], max_length=10
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("escalated", "Escalated"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Chat Session",
                "verbose_name_plural": "Chat Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RemoteWorkRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("short_term", "Short-Term Remote Work"),
                            ("permanent_transfer", "Permanent Transfer"),
                        ],
                        default="short_term",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("escalated", "Escalated"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "maersk_entity",
                    models.CharField(
                        help_text="Maersk entity for this request", max_length=100
                    ),
                ),
                (
                    "home_country",
                    models.CharField(help_text="Country of employment", max_length=100),
                ),
                (
                    "destination_country",
                    models.CharField(
                        help_text="Country where remote work will take place",
                        max_length=100,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("duration_days", models.PositiveIntegerField(editable=False)),
                (
                    "has_right_to_work",
                    models.BooleanField(
                        default=False,
                        help_text="Does the employee have the right to work in the destination country?",
                    ),
                ),
                (
                    "is_sales_role",
                    models.BooleanField(
                        default=False,
                        help_text="Is this a sales role with contract signing authority?",
                    ),
                ),
                (
                    "manager_approval_document",
                    models.FileField(
                        blank=True,
                        help_text="Manager approval document",
                        null=True,
                        upload_to="approvals/%Y/%m/",
                    ),
                ),
                (
                    "decision_reason",
                    models.TextField(
                        blank=True, help_text="Reason for approval/rejection/escalation"
                    ),
                ),
                (
                    "escalation_note",
                    models.TextField(
                        blank=True, help_text="Additional notes for escalated requests"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Remote Work Request",
                "verbose_name_plural": "Remote Work Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
