# Generated by Django 4.2.28 on 2026-02-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="remoteworkrequest",
            name="confirmed_role_eligible",
            field=models.BooleanField(
                default=False,
                help_text="Employee confirmed they are not in any ineligible role category",
            ),
        ),
        migrations.AddField(
            model_name="remoteworkrequest",
            name="exception_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason for requesting an exception to normal limits",
            ),
        ),
        migrations.AddField(
            model_name="remoteworkrequest",
            name="ineligible_role_categories",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of ineligible role categories the employee confirmed they are NOT in",
            ),
        ),
        migrations.AddField(
            model_name="remoteworkrequest",
            name="is_exception_request",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is an exception request (>20 days or >14 consecutive)",
            ),
        ),
        migrations.AddField(
            model_name="remoteworkrequest",
            name="manager_email",
            field=models.EmailField(
                blank=True,
                help_text="Approving manager's email address",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="remoteworkrequest",
            name="manager_first_name",
            field=models.CharField(
                blank=True, help_text="Approving manager's first name", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="remoteworkrequest",
            name="manager_last_name",
            field=models.CharField(
                blank=True, help_text="Approving manager's last name", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="remoteworkrequest",
            name="manager_middle_name",
            field=models.CharField(
                blank=True, help_text="Approving manager's middle name", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="remoteworkrequest",
            name="manager_approval_document",
            field=models.FileField(
                blank=True,
                help_text="Manager approval document (email/PDF)",
                null=True,
                upload_to="approvals/%Y/%m/",
            ),
        ),
    ]
